/// Flutter icons SendIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SendIcon
///      fonts:
///       - asset: fonts/SendIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class SendIcon {
  SendIcon._();

  static const _kFontFam = 'SendIcon';
  static const String _kFontPkg = null;

  static const IconData send = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
